-- GENERATED by tools/librarian-books.py - do not edit, rerun the script.
-- Source: https://foreverchanges.pro/library-books (page updated 2026-09-24, beta build 1.60.1.70205).
-- Turn-in quest IDs: Wowhead Forever (see QUESTS in the script). Extra books and notes:
-- Wowhead Forever + zockify.com/forever/library-books (EXTRA_BOOKS / EXTRA_NOTES).
local _, ns = ...

ns.DataSource = { url = "https://foreverchanges.pro/library-books", updated = "2026-09-24", build = "1.60.1.70205" }

ns.Goals = {
    { quest = 78150, title = "Friend of the Library", books = 10, level = 1, rewards = { { item = 277203, name = "Scholarly Pendant", role = "caster" }, { item = 277204, name = "Erudite's Amulet", role = "physical" } } },
    { quest = 79536, title = "Greater Friend of the Library", books = 20, level = 20, rewards = { { item = 281635, name = "Philanthropist's Ring", role = "caster" }, { item = 281634, name = "Field Researcher's Loop", role = "physical" } } },
    { quest = 82208, title = "Greater Friend of the Library", books = 25, level = 30, rewards = { { item = 277254, name = "Truthseeker's Bow", role = "physical", classes = { "WARRIOR", "HUNTER", "ROGUE" } }, { item = 277258, name = "Crest of Elucidation", role = "caster", classes = { "WARRIOR", "PALADIN", "SHAMAN" }, level = 40 }, { item = 277260, name = "Researcher's Night Light", role = "caster", level = 40 } } },
}

ns.Librarians = {
    { npc = 211033, name = "Garion Wendell", side = "Alliance", map = 1453, x = 37.6, y = 80.8, area = "Mage Quarter" },
    { npc = 211022, name = "Owen Thadd", side = "Horde", map = 1458, x = 73.4, y = 33.0, area = "Magic Quarter" },
}

-- Turn-in for the level 60 set (books with trainer = true).
ns.Trainers = {
    { npc = 5497, name = "Jennea Cannon", side = "Alliance", map = 1453, x = 38.5, y = 79.5, area = "Mage Quarter" },
    { npc = 7825, name = "Oran Snakewrithe", side = "Horde", map = 1458, x = 73.5, y = 32.5, area = "Magic Quarter" },
}

-- uiMapID -> zone. continent: 1414 Kalimdor, 1415 Eastern Kingdoms.
ns.Zones = {
    [1413] = { name = "The Barrens", continent = 1414, level = "10-25", side = "Horde" },
    [1416] = { name = "Alterac Mountains", continent = 1415, level = "27-39", side = "Contested" },
    [1417] = { name = "Arathi Highlands", continent = 1415, level = "30-40" },
    [1418] = { name = "Badlands", continent = 1415, level = "35-45" },
    [1419] = { name = "Blasted Lands", continent = 1415, level = "45-55" },
    [1420] = { name = "Tirisfal Glades", continent = 1415, level = "5-12", side = "Horde" },
    [1421] = { name = "Silverpine Forest", continent = 1415, level = "10-20", side = "Horde" },
    [1422] = { name = "Western Plaguelands", continent = 1415, level = "51-58" },
    [1423] = { name = "Eastern Plaguelands", continent = 1415, level = "53-60" },
    [1425] = { name = "The Hinterlands", continent = 1415, level = "40-50" },
    [1427] = { name = "Searing Gorge", continent = 1415, level = "43-50" },
    [1428] = { name = "Burning Steppes", continent = 1415, level = "50-58" },
    [1429] = { name = "Elwynn Forest", continent = 1415, level = "5-10", side = "Alliance" },
    [1431] = { name = "Duskwood", continent = 1415, level = "19-30", side = "Contested" },
    [1432] = { name = "Loch Modan", continent = 1415, level = "10-18", side = "Alliance" },
    [1434] = { name = "Stranglethorn Vale", continent = 1415, level = "30-44", side = "Contested" },
    [1435] = { name = "Swamp of Sorrows", continent = 1415, level = "35-45" },
    [1436] = { name = "Westfall", continent = 1415, level = "9-18", side = "Alliance" },
    [1437] = { name = "Wetlands", continent = 1415, level = "20-30", side = "Contested" },
    [1439] = { name = "Darkshore", continent = 1414, level = "11-19", side = "Alliance" },
    [1441] = { name = "Thousand Needles", continent = 1414, level = "24-35", side = "Contested" },
    [1442] = { name = "Stonetalon Mountains", continent = 1414, level = "15-25", side = "Contested" },
    [1443] = { name = "Desolace", continent = 1414, level = "30-40" },
    [1445] = { name = "Dustwallow Marsh", continent = 1414, level = "36-43", side = "Contested" },
    [1446] = { name = "Tanaris", continent = 1414, level = "40-50" },
    [1447] = { name = "Azshara", continent = 1414, level = "45-55" },
    [1448] = { name = "Felwood", continent = 1414, level = "48-55" },
    [1452] = { name = "Winterspring", continent = 1414, level = "53-60" },
    [1454] = { name = "Orgrimmar", continent = 1414, side = "Horde" },
    [1455] = { name = "Ironforge", continent = 1415, side = "Alliance" },
}

-- spot.area = the game's area ID for the place (the addon reads its localised name).
-- tier = the quest level of the set (20 first set, 35 / 45 / 60 later sets).
-- noForeverQuest = the turn-in quest is missing from
-- Wowhead's Forever database; unplaced = no known location, notInForever = the site
-- says the book cannot be had on Forever (both with spots empty); trainer = turned in
-- to a mage trainer (ns.Trainers), not a librarian; extra = not on the page (script's
-- EXTRA_BOOKS, from Wowhead + zockify.com).
ns.Books = {
    {
        item = 203755, quest = 79092, tier = 20,
        name = "Archmage Theocritus' Research Journal",
        flavour = "Research notes from the Tower of Azora.",
        spots = {
            { map = 1429, x = 65.4, y = 70.1, area = 91, container = "Library Book", place = "Tower of Azora" },
        },
    },
    {
        item = 203754, quest = 79091, tier = 20,
        name = "Archmage Antonidas: The Unabridged Autobiography",
        flavour = "Somewhat self-indulgent, but nevertheless a fine addition to any library's collection.",
        spots = {
            { map = 1455, x = 75.7, y = 10.5, container = "Library Book", note = "Horde characters can take it too. A Horde reader looted it here, and the librarian in Undercity offered its quest. They told us on September 30, 2026." },
        },
    },
    {
        item = 209845, quest = 78142, tier = 20,
        name = "Bewitchments and Glamours",
        flavour = "Spells for manipulation and deception.",
        spots = {
            { map = 1436, x = 45.4, y = 70.4, area = 20, container = "Spellbook", place = "Moonbrook" },
        },
    },
    {
        item = 208860, quest = 79093, tier = 20,
        name = "Rumi of Gnomeregan: The Collected Works",
        flavour = "The writings of a notable Gnome mage.",
        spots = {
            { map = 1436, x = 52.7, y = 53.8, area = 108, container = "Gnomish Tome", place = "Sentinel Hill" },
            { map = 1432, x = 35.6, y = 48.9, area = 144, container = "Gnomish Tome", place = "Thelsamar" },
        },
    },
    {
        item = 209849, quest = 78147, tier = 20,
        name = "Crimes Against Anatomy",
        flavour = "Written by Doctor Krastinov.",
        spots = {
            { map = 1431, x = 16.6, y = 28.5, area = 799, container = "Spellbook", place = "The Darkened Bank", note = "Inside the catacomb there, in the last room, on a wooden table at the far end. A reader found it there on September 29, 2026." },
        },
    },
    {
        item = 209850, quest = 78148, tier = 20,
        name = "Runes of the Sorcerer-Kings",
        flavour = "A relic of the mighty ogre empires of Draenor.",
        spots = {
            { map = 1432, x = 77.4, y = 14.0, area = 143, container = "Scrolls", place = "Mo'grosh Stronghold" },
        },
    },
    {
        item = 209848, quest = 78146, tier = 20,
        name = "Goaz Scrolls",
        flavour = "Written in lost Titan script, but nevertheless a fine addition to any library's collection.",
        spots = {
            { map = 1437, x = 33.6, y = 47.9, area = 118, container = "Scrolls", place = "Whelgar's Excavation Site" },
        },
    },
    {
        item = 209844, quest = 78127, tier = 20,
        name = "The Dalaran Digest, Vol. 23",
        flavour = "Arcane research of the Kirin Tor.",
        spots = {
            { map = 1421, x = 63.5, y = 63.1, area = 233, container = "Dalaran Digest", place = "Ambermill" },
        },
    },
    {
        item = 208185, quest = 79095, tier = 20,
        name = "The Apothecary's Metaphysical Primer",
        flavour = "Elementary notes on arcane theory and spell research, compiled by Archmage Rotwick of the Royal Apothecary Society.",
        spots = {
            { map = 1420, x = 59.4, y = 52.3, area = 159, container = "Apothecary Society Primer", place = "Brill" },
        },
    },
    {
        item = 209843, quest = 78124, tier = 20,
        name = "Nar'thalas Almanac, Vol. 74",
        flavour = "Arcane research of the ancient quel'dorei.",
        spots = {
            { map = 1439, x = 59.6, y = 22.2, area = 443, container = "Scrolls", place = "Ruins of Mathystra" },
        },
    },
    {
        item = 209847, quest = 78145, tier = 20,
        name = "Arcanic Systems Manual",
        flavour = "Poorly-organized troubleshooting tips for goblin technology.",
        spots = {
            { map = 1413, x = 56.3, y = 8.8, area = 382, container = "Manual", place = "The Sludge Fen" },
        },
    },
    {
        item = 208800, quest = 79097, tier = 20,
        name = "Baxtan: On Destructive Magics",
        flavour = "The writings of a notable Goblin mage.",
        spots = {
            { map = 1413, x = 62.7, y = 36.3, area = 392, container = "Goblin Tome", place = "Ratchet" },
        },
    },
    {
        item = 209846, quest = 78143, tier = 20,
        name = "Secrets of the Dreamers",
        flavour = "Observations and insights on the Emerald Dream.",
        spots = {
            { map = 1413, x = 46.0, y = 36.5, place = "cave entrance", note = "Location and Scrolls container confirmed by two players on September 22, 2026. Enter the cave at Lushwater Oasis (The Barrens, 46.0, 36.5), then head to the Cavern of Mists, near the Wailing Caverns instance entrance. Look for Scrolls at 52.8, 54.7 on the cave map." },
        },
    },
    {
        item = 209851, quest = 78149, tier = 20,
        name = "Fury of the Land",
        flavour = "Closely guarded shamanistic secrets of the Grimtotem clan.",
        spots = {
            { map = 1442, x = 74.4, y = 85.7, area = 2537, container = "Scrolls", place = "Grimtotem Post" },
        },
    },
    {
        item = 207972, quest = 79094, tier = 20,
        name = "The Lessons of Ta'zo",
        flavour = "A tracing of etchings written by a great Troll mage.",
        spots = {
            { map = 1454, x = 38.7, y = 78.4, container = "Ta'zo Mural", note = "Location confirmed by a player on September 22, 2026." },
        },
    },
    {
        item = 213165, quest = 79535, tier = 35,
        name = "Basilisks: Should Petrification be Feared?",
        flavour = "Attempted research on the use of basilisk parts as reagents.",
        spots = {
            { map = 1434, x = 41.4, y = 50.9, area = 310, container = "Research Notes", place = "Crystalvein Mine", note = "On a wooden platform to the right of the mine's mouth, so you never go into the mine itself." },
        },
    },
    {
        item = 215683, quest = 79947, tier = 35,
        name = "Geomancy: The Stone-Cold Truth",
        flavour = "Theories on the origin and usage of elemental magic.",
        spots = {
            { map = 1441, x = 34.4, y = 40.1, area = 2097, container = "Scrolls", place = "Darkcloud Pinnacle", note = "The lowest zone of the eight, and the path up the pinnacle starts at 31.0, 37.0. The scrolls are in the largest hut." },
        },
    },
    {
        item = 215815, quest = 79948, tier = 35,
        name = "Defensive Magics 101",
        flavour = "An introductory guide to defensive magic and barriers.",
        spots = {
            { map = 1416, x = 48.4, y = 57.6, area = 1357, container = "Manual", place = "Gallows' Corner", note = "The first tower you meet entering the ogre fortress, from Tarren Mill or from Strahnbrad. The manual is inside it." },
        },
    },
    {
        item = 215822, quest = 79952, tier = 35,
        name = "RwlRwlRwlRwl!",
        flavour = "The strange passages are faint but somewhat readable despite water damage.",
        spots = {
            { map = 1445, x = 57.2, y = 20.8, area = 502, container = "Waterlogged Book", place = "Witch Hill", note = "On the ground at the eastern edge of the murloc camp: you can walk to it and walk back out." },
        },
    },
    {
        item = 215816, quest = 79949, tier = 35,
        name = "A Web of Lies: Debunking Myths and Legends",
        spots = {
            { map = 1417, x = 73.6, y = 65.2, area = 317, container = "Scrolls", place = "Witherbark Village" },
        },
    },
    {
        item = 215817, quest = 79950, tier = 35,
        name = "Demons and You",
        spots = {
            { map = 1443, x = 55.1, y = 26.2, area = 599, container = "Mysterious Book", place = "Thunder Axe Fortress" },
        },
    },
    {
        item = 215820, quest = 79951, tier = 35,
        name = "Mummies: A Guide to the Unsavory Undead",
        spots = {
            { map = 1418, x = 56.7, y = 39.9, container = "Scrolls" },
        },
    },
    {
        item = 215824, quest = 79953, tier = 35, noForeverQuest = true,
        name = "A Luddite's Guide to Caring for Your Demonic Pet",
        spots = {
            { map = 1435, x = 61.4, y = 22.4, area = 76, container = "Book", place = "Fallow Sanctuary", note = "Players report that the book sits inside a cage that opens with the Rusted Cage Key. A reader found the key listed on Wowhead as a rare drop, about 1%, of the Muckdweller murlocs around the cage. Looting it through the bars no longer works in Forever (Wowhead comment, 2026-09-30)." },
        },
    },
    {
        item = 220345, quest = 81947, tier = 45,
        name = "Sanguine Sorcery",
        spots = {
            { map = 1435, x = 70.0, y = 51.0, area = 74, place = "Pool of Tears", note = "On top of the Sunken Temple, outside the dungeon." },
        },
    },
    {
        item = 220346, quest = 81949, tier = 45,
        name = "Legends of the Tidesages",
        spots = {
            { map = 1446, x = 72.7, y = 47.8, area = 1336, container = "Book", place = "Lost Rigger Cove" },
        },
    },
    {
        item = 220347, quest = 81951, tier = 45, noForeverQuest = true,
        name = "The Liminal and the Arcane",
        notInForever = "Not available in Forever: the book sits in Oneiros, behind the Nightmare Incursions portal of Season of Discovery, which Forever does not have.",
        spots = {
        },
    },
    {
        item = 220348, quest = 81952, tier = 45,
        name = "Everyday Etiquette",
        spots = {
            { map = 1447, x = 20.7, y = 62.0, area = 1236, container = "Book", place = "Haldarr Encampment" },
        },
    },
    {
        item = 220349, quest = 81953, tier = 45,
        name = "Stonewrought Design",
        spots = {
            { map = 1428, x = 29.0, y = 28.9, area = 25, place = "Blackrock Mountain", note = "On the altar of the tomb in the middle of Blackrock Mountain, where a dwarf's ghost stands. You reach it without entering a dungeon. Another report places it inside Blackrock Mountain, Center Vault, on the large platform (about 48.6, 64.2 on the Blackrock Mountain map)." },
        },
    },
    {
        item = 220350, quest = 81954, tier = 45,
        name = "Venomous Journeys",
        spots = {
            { map = 1425, x = 36.0, y = 72.8, area = 353, container = "Book", place = "Shadra'Alor" },
        },
    },
    {
        item = 220352, quest = 81955, tier = 45,
        name = "A Mind of Metal",
        spots = {
            { map = 1427, x = 37.8, y = 49.3, area = 246, container = "Book", place = "The Cauldron" },
        },
    },
    {
        item = 220353, quest = 81956, tier = 45,
        name = "Conjurer's Codex",
        spots = {
            { map = 1419, x = 55.4, y = 32.2, container = "Book" },
        },
    },
    {
        item = 228134, quest = 84397, tier = 60, trainer = true,
        name = "Northern Kalimdor - A Comprehensive Guide",
        spots = {
            { map = 1448, x = 65.2, y = 3.3, container = "Book", note = "In the cave of Timbermaw Hold, the tunnel between Felwood and Winterspring. A player found it there on September 24, 2026." },
        },
    },
    {
        item = 228141, quest = 84402, tier = 60, trainer = true,
        name = "Necromancy 101",
        spots = {
            { map = 1422, x = 69.4, y = 72.8, area = 2298, place = "Caer Darrow", note = "On a table in the ruined keep of Caer Darrow, at the top of the Scholomance building, outside the dungeon. Two players found it there on September 23 and 24, 2026." },
        },
    },
    {
        item = 228132, quest = 84395, tier = 60, trainer = true,
        name = "Undead Potatoes",
        spots = {
            { map = 1422, x = 38.2, y = 54.6, area = 199, container = "Book", place = "Felstone Field", note = "Wowhead's Forever database puts it here (read on October 1, 2026). No player has confirmed it to us yet." },
        },
    },
    {
        item = 228135, quest = 84398, tier = 60, trainer = true,
        name = "A Study of the Light",
        spots = {
            { map = 1423, x = 71.8, y = 48.2, area = 2268, place = "Light's Hope Chapel", note = "Inside the chapel building of Light's Hope Chapel, the Argent Dawn's camp. Three players reported it there on September 24, 2026, one of them with coordinates." },
            { map = 1423, x = 81.7, y = 57.8, container = "Book", note = "Not confirmed in Forever: the Season of Discovery spot, still in Wowhead's Forever data." },
        },
    },
    {
        item = 228138, quest = 84400, tier = 60, trainer = true,
        name = "The Knight and the Lady",
        spots = {
            { map = 1423, x = 54.4, y = 51.1, area = 2264, container = "Book", place = "Corin's Crossing", note = "In a small house by the lake. A reader picked it up there on October 2, 2026." },
            { map = 1423, x = 47.3, y = 42.3, container = "Book", note = "In a burned house by the lake (zockify.com, wowsod.pro). Players reach it on a death run." },
        },
    },
    {
        item = 228140, quest = 84401, tier = 60, trainer = true,
        name = "Scourge: Undead Menace or Misunderstood?",
        spots = {
            { map = 1423, x = 26.5, y = 15.0, container = "Book", place = "Stratholme bridge", note = "On a table to the right before crossing the bridge to Stratholme, outside the instance (zockify.com, wowsod.pro). Two undead stand close by." },
            { map = 1423, x = 31.2, y = 21.0, area = 2277, container = "Book", place = "Plaguewood", note = "Wowhead's Forever database puts it here (read on October 1, 2026). No player has confirmed it to us yet." },
        },
    },
    {
        item = 228136, quest = 84399, tier = 60, trainer = true,
        name = "Ka-Boom!",
        spots = {
            { map = 1452, x = 60.7, y = 37.7, area = 2255, place = "Everlook", note = "On a shelf behind the alchemy supplier in Everlook. A player confirmed it there on September 24, 2026." },
        },
    },
    {
        item = 228133, quest = 84396, tier = 60, trainer = true, extra = true,
        name = "Magma or Lava?",
        spots = {
            { map = 1428, x = 29.0, y = 28.9, area = 25, place = "Blackrock Mountain", note = "Inside Blackrock Mountain on a platform before the Blackrock Depths entrance, not in the instance: 48.4, 63.6 on the Blackrock Mountain map. The pin marks the mountain, not the book." },
        },
    },
    {
        item = 210177, quest = 79096, tier = 20, noForeverQuest = true,
        name = "Ataeric: On Arcane Curiosities",
        unplaced = "Not in the Sepulcher: players report searching it, downstairs near Sebastian Meloche included, and finding nothing, even though Wowhead's Forever database still lists it there. Not behind Arugal in Shadowfang Keep either: the book there is the Black Tome, a quest item unrelated to the library. If you find it, tell us where.",
        spots = {
        },
    },
}
